/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.estadisticasnba;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.FillPatternType;
import org.apache.poi.ss.usermodel.Font;
import org.apache.poi.ss.usermodel.HorizontalAlignment;
import org.apache.poi.ss.usermodel.IndexedColors;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.VerticalAlignment;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author dl260
 */
public class EstadisticasNBA extends javax.swing.JFrame {

    /**
     * Creates new form Estadisticas_NBA
     */
    public EstadisticasNBA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Insertar_datos = new javax.swing.JButton();
        NombreJugador = new javax.swing.JTextField();
        T_2Puntos = new javax.swing.JSpinner();
        T_3Puntos = new javax.swing.JSpinner();
        T_3PuntosMetidos = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        T_2PuntosMetidos = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre jugador");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel2.setText("Tiros de 2 puntos");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel3.setText("Tiros de 3 puntos");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel4.setText("Tiros de 3 metidos");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        Insertar_datos.setText("Insertar datos");
        Insertar_datos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Insertar_datosMouseClicked(evt);
            }
        });
        jPanel1.add(Insertar_datos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 110, 30));

        NombreJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreJugadorActionPerformed(evt);
            }
        });
        jPanel1.add(NombreJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 110, 30));
        jPanel1.add(T_2Puntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, -1, -1));
        jPanel1.add(T_3Puntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, -1));
        jPanel1.add(T_3PuntosMetidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, -1));

        jLabel5.setText("Tiros de 2 metidos");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));
        jPanel1.add(T_2PuntosMetidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Insertar_datosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Insertar_datosMouseClicked
        String nombreJugador = NombreJugador.getText();
        int tiros2 = (int) T_2Puntos.getValue();
        int tiros3 = (int) T_3Puntos.getValue();
        int tirosMetidos2 = (int) T_2PuntosMetidos.getValue();
        int tirosMetidos3 = (int) T_3PuntosMetidos.getValue();

        if (tirosMetidos2 == 0 || tirosMetidos3 == 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "El número de tiros metidos no puede ser 0.");
            return;
        }

        int tirosTotales = tirosMetidos2 + tirosMetidos3;
        double porcentajeFG = ((double) (tiros2 + tiros3) / tirosTotales) * 100;
        double porcentajeEFG = ((double) (tiros2 + 1.5 * tiros3) / tirosTotales) * 100;

        String[][] datos = {
            {nombreJugador, String.valueOf(tiros2), String.valueOf(tiros3),
             String.valueOf(tirosMetidos2), String.valueOf(tirosMetidos3), String.format("%.2f", porcentajeFG),
             String.format("%.2f", porcentajeEFG)}
        };

        try {
            crearArchivo("EstadisticasNBA.xlsx", datos);
            javax.swing.JOptionPane.showMessageDialog(this, "Datos insertados correctamente en EstadisticasNBA.xlsx");
        } catch (IOException ex) {
            Logger.getLogger(EstadisticasNBA.class.getName()).log(Level.SEVERE, null, ex);
            javax.swing.JOptionPane.showMessageDialog(this, "Error al insertar datos en el archivo.");
        }
    }//GEN-LAST:event_Insertar_datosMouseClicked

    private void NombreJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreJugadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreJugadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstadisticasNBA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstadisticasNBA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstadisticasNBA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstadisticasNBA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EstadisticasNBA().setVisible(true);
            }
        });
    }
    
    public static void crearArchivo(String nombreArchivo, String[][] datos) throws IOException {
        Workbook libroExcel;
        Sheet hoja;
        int ultimaFila = 0;
        
        File archivoExcel = new File(nombreArchivo);
        if (archivoExcel.exists()) {
            try (FileInputStream entrada = new FileInputStream(archivoExcel)) {
                libroExcel = new XSSFWorkbook(entrada);
                hoja = libroExcel.getSheetAt(0);
                ultimaFila = hoja.getLastRowNum() + 1;
            }
        } else {
            libroExcel = new XSSFWorkbook();
            hoja = libroExcel.createSheet("NBA_estadisticas");

            Row fila = hoja.createRow(0);
            fila.createCell(0).setCellValue("Nombre Jugador");
            fila.createCell(1).setCellValue("Nº Tiros de 2");
            fila.createCell(2).setCellValue("Nº Tiros de 3");
            fila.createCell(3).setCellValue("Tiros de 2 metidos");
            fila.createCell(4).setCellValue("Tiros de 3 metidos");
            fila.createCell(5).setCellValue("%FG");
            fila.createCell(6).setCellValue("%eFG");

            fila.setHeightInPoints(25);

            ultimaFila = 1;
        }

        CellStyle estilo = libroExcel.createCellStyle();
        Font fuente = libroExcel.createFont();
        fuente.setBold(true);
        fuente.setColor(IndexedColors.BLUE.getIndex());
        fuente.setFontName("Arial");
        estilo.setFont(fuente);
        estilo.setFillForegroundColor(IndexedColors.YELLOW.getIndex());
        estilo.setFillPattern(FillPatternType.SOLID_FOREGROUND);
        estilo.setAlignment(HorizontalAlignment.CENTER);
        estilo.setVerticalAlignment(VerticalAlignment.TOP);

        for (int i = 0; i < datos.length; i++) {
            Row fila = hoja.createRow(ultimaFila + i);
            for (int j = 0; j < datos[i].length; j++) {
                Cell celda = fila.createCell(j);
                celda.setCellValue(datos[i][j]);
                celda.setCellStyle(estilo);
            }
        }

       for (int col = 0;col < datos[0].length; col++){
           hoja.setColumnWidth(col, 20*256);
       }

        try (FileOutputStream salida = new FileOutputStream(nombreArchivo)) {
            libroExcel.write(salida);
        } catch (IOException ex) {
            ex.printStackTrace();
        }

        libroExcel.close();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Insertar_datos;
    private javax.swing.JTextField NombreJugador;
    private javax.swing.JSpinner T_2Puntos;
    private javax.swing.JSpinner T_2PuntosMetidos;
    private javax.swing.JSpinner T_3Puntos;
    private javax.swing.JSpinner T_3PuntosMetidos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
