/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.estadisticasnba;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.FillPatternType;
import org.apache.poi.ss.usermodel.Font;
import org.apache.poi.ss.usermodel.HorizontalAlignment;
import org.apache.poi.ss.usermodel.IndexedColors;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.VerticalAlignment;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author dl260
 */
public class EstadisticasNBA extends javax.swing.JFrame {

    /**
     * Creates new form Estadisticas_NBA
     */
    public EstadisticasNBA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Insertar_datos = new javax.swing.JButton();
        PanelTabuladoDatos = new javax.swing.JTabbedPane();
        PanelDatos1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NombreJugador = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        T_2Puntos = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        T_2PuntosMetidos = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        T_3Puntos = new javax.swing.JSpinner();
        T_3PuntosMetidos = new javax.swing.JSpinner();
        T_Libres = new javax.swing.JSpinner();
        T_LibresMetidos = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        PanelDatos2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        T_rebotes = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        T_taponesRecibidos = new javax.swing.JSpinner();
        T_asistencias = new javax.swing.JSpinner();
        T_robos = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        T_taponesAfavor = new javax.swing.JSpinner();
        T_perdidas = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Insertar_datos.setText("Insertar datos");
        Insertar_datos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Insertar_datosMouseClicked(evt);
            }
        });
        jPanel1.add(Insertar_datos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 110, 30));

        PanelTabuladoDatos.setMinimumSize(new java.awt.Dimension(100, 100));

        PanelDatos1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Nombre jugador");
        PanelDatos1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 16, 110, 20));

        NombreJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreJugadorActionPerformed(evt);
            }
        });
        PanelDatos1.add(NombreJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 110, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Tiros de 2 puntos");
        PanelDatos1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 130, 30));
        PanelDatos1.add(T_2Puntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 100, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Tiros de 2 metidos");
        PanelDatos1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 50, 140, 30));
        PanelDatos1.add(T_2PuntosMetidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 100, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Tiros de 3 puntos");
        PanelDatos1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 130, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Tiros de 3 metidos");
        PanelDatos1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 140, 30));
        PanelDatos1.add(T_3Puntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 100, 30));
        PanelDatos1.add(T_3PuntosMetidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 100, 30));
        PanelDatos1.add(T_Libres, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 100, 30));
        PanelDatos1.add(T_LibresMetidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 100, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Tiros Libres");
        PanelDatos1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 130, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Tiros Libres metidos");
        PanelDatos1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 140, 30));

        PanelTabuladoDatos.addTab("Datos1", PanelDatos1);

        PanelDatos2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Tapones a favor");
        PanelDatos2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 100, 30));
        PanelDatos2.add(T_rebotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 100, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Tapones reibidos");
        PanelDatos2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 120, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Asistencias");
        PanelDatos2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 100, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Robos");
        PanelDatos2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 100, 30));
        PanelDatos2.add(T_taponesRecibidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 100, 30));
        PanelDatos2.add(T_asistencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 100, 30));
        PanelDatos2.add(T_robos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 100, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Rebotes");
        PanelDatos2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Perdidas");
        PanelDatos2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 100, 30));
        PanelDatos2.add(T_taponesAfavor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 100, 30));
        PanelDatos2.add(T_perdidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 100, 30));

        PanelTabuladoDatos.addTab("Datos2", PanelDatos2);

        jPanel1.add(PanelTabuladoDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 360));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Insertar_datosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Insertar_datosMouseClicked
        String nombreJugador = NombreJugador.getText();
        int tiros2 = (int) T_2Puntos.getValue();
        int tiros3 = (int) T_3Puntos.getValue();
        int tirosLibres = (int) T_Libres.getValue();
        int tirosMetidos2 = (int) T_2PuntosMetidos.getValue();
        int tirosMetidos3 = (int) T_3PuntosMetidos.getValue();
        int tirosLibresMetidos = (int) T_LibresMetidos.getValue();
        int Puntos = tirosMetidos2 + tirosMetidos3 + tirosLibresMetidos;
        int Rebotes = (int) T_rebotes.getValue();
        int Asistencias = (int) T_asistencias.getValue();
        int Robos = (int) T_robos.getValue();
        int TaponesFavor = (int) T_taponesAfavor.getValue();
        int Perdidas = (int) T_perdidas.getValue();
        int TaponesRecibidos = (int) T_taponesRecibidos.getValue();
        int TirosFallados = (tiros2 + tiros3 + tirosLibres) - Puntos;
        int TirosLibresFallados = tirosLibres - tirosLibresMetidos;

        if (tirosMetidos2 == 0 || tirosMetidos3 == 0 || tirosLibresMetidos == 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "El número de tiros metidos no puede ser 0.");
            return;
        }

        int tirosTotales = tirosMetidos2 + tirosMetidos3;
        double porcentajeFG = ((double) (tiros2 + tiros3) / tirosTotales) * 100;
        double porcentajeEFG = ((double) (tiros2 + 1.5 * tiros3) / tirosTotales) * 100;
        double porcetajeTS = (tirosTotales / (2.0*(tirosMetidos2 + tirosMetidos3 + 0.44 * tirosLibresMetidos))) * 100;
        double Valoracion = (Puntos + Rebotes + Asistencias + Robos + TaponesFavor) - (TirosFallados + TirosLibresFallados + Perdidas + TaponesRecibidos);

        String[][] datos = {
            {nombreJugador, String.valueOf(tiros2), String.valueOf(tiros3),String.valueOf(tirosLibres),
             String.valueOf(tirosMetidos2), String.valueOf(tirosMetidos3), String.valueOf(tirosLibresMetidos),
             String.format("%.2f", porcentajeFG), String.format("%.2f", porcentajeEFG), String.format("%.2f", porcetajeTS), String.valueOf(Valoracion)}
        };

        try {
            crearArchivo("EstadisticasNBA.xlsx", datos);
            javax.swing.JOptionPane.showMessageDialog(this, "Datos insertados correctamente en EstadisticasNBA.xlsx");
        } catch (IOException ex) {
            Logger.getLogger(EstadisticasNBA.class.getName()).log(Level.SEVERE, null, ex);
            javax.swing.JOptionPane.showMessageDialog(this, "Error al insertar datos en el archivo.");
        }
    }//GEN-LAST:event_Insertar_datosMouseClicked

    private void NombreJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreJugadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreJugadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstadisticasNBA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstadisticasNBA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstadisticasNBA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstadisticasNBA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EstadisticasNBA().setVisible(true);
            }
        });
    }
    
    public static void crearArchivo(String nombreArchivo, String[][] datos) throws IOException {
        Workbook libroExcel;
        Sheet hoja;
        int ultimaFila = 0;

        File archivoExcel = new File(nombreArchivo);
        if (archivoExcel.exists()) {
            try (FileInputStream entrada = new FileInputStream(archivoExcel)) {
                libroExcel = new XSSFWorkbook(entrada);
                hoja = libroExcel.getSheetAt(0);

                ultimaFila = hoja.getLastRowNum();
                Row ultima = hoja.getRow(ultimaFila);
                if (ultima != null && ultima.getCell(0) != null &&
                    "Promedios".equals(ultima.getCell(0).getStringCellValue())) {
                    hoja.removeRow(ultima);
                    ultimaFila--;
                }
            }
        } else {
            libroExcel = new XSSFWorkbook();
            hoja = libroExcel.createSheet("NBA_estadisticas");

            Row fila = hoja.createRow(0);
            fila.createCell(0).setCellValue("Nombre Jugador");
            fila.createCell(1).setCellValue("Nº Tiros de 2");
            fila.createCell(2).setCellValue("Nº Tiros de 3");
            fila.createCell(3).setCellValue("Nº Tiros Libres");
            fila.createCell(4).setCellValue("Tiros de 2 metidos");
            fila.createCell(5).setCellValue("Tiros de 3 metidos");
            fila.createCell(6).setCellValue("Tiros Libres metidos");
            fila.createCell(7).setCellValue("%FG");
            fila.createCell(8).setCellValue("%eFG");
            fila.createCell(9).setCellValue("%TS");
            fila.createCell(10).setCellValue("Valoracion");

            fila.setHeightInPoints(25);
            ultimaFila = 0;
        }

        CellStyle estilo = libroExcel.createCellStyle();
        Font fuente = libroExcel.createFont();
        fuente.setBold(true);
        fuente.setColor(IndexedColors.BLUE.getIndex());
        fuente.setFontName("Arial");
        estilo.setFont(fuente);
        estilo.setFillForegroundColor(IndexedColors.YELLOW.getIndex());
        estilo.setFillPattern(FillPatternType.SOLID_FOREGROUND);
        estilo.setAlignment(HorizontalAlignment.CENTER);
        estilo.setVerticalAlignment(VerticalAlignment.TOP);

        for (int i = 0; i < datos.length; i++) {
            Row fila = hoja.createRow(ultimaFila + 1 + i);
            for (int j = 0; j < datos[i].length; j++) {
                Cell celda = fila.createCell(j);
                celda.setCellValue(datos[i][j]);
                celda.setCellStyle(estilo);
            }
        }
        ultimaFila = hoja.getLastRowNum();

        double sumaTiros2 = 0, sumaTiros3 = 0, sumaLibres = 0, sumaMetidos2 = 0, sumaMetidos3 = 0, sumaMetidosLibres = 0;
        double sumaFG = 0, sumaEFG = 0, sumaTS = 0, sumaValoracion = 0;
        int filasDatos = 0;

        for (int i = 1; i <= ultimaFila; i++) {
            Row fila = hoja.getRow(i);
            if (fila != null) {
                sumaTiros2 += getNumericValue(fila.getCell(1));
                sumaTiros3 += getNumericValue(fila.getCell(2));
                sumaLibres += getNumericValue(fila.getCell(3));
                sumaMetidos2 += getNumericValue(fila.getCell(4));
                sumaMetidos3 += getNumericValue(fila.getCell(5));
                sumaMetidosLibres += getNumericValue(fila.getCell(6));
                sumaFG += getNumericValue(fila.getCell(7));
                sumaEFG += getNumericValue(fila.getCell(8));
                sumaTS += getNumericValue(fila.getCell(9));
                sumaValoracion += getNumericValue(fila.getCell(10));
                filasDatos++;
            }
        }

        if (filasDatos > 0) {
            double mediaFG = sumaFG / filasDatos;
            double mediaEFG = sumaEFG / filasDatos;
            double mediaTS = sumaTS / filasDatos;
            double mediaValoracion = sumaValoracion / filasDatos;

            Row filaMedias = hoja.createRow(ultimaFila + 1);
            filaMedias.createCell(0).setCellValue("Promedios");
            filaMedias.createCell(1).setCellValue(sumaTiros2 / filasDatos);
            filaMedias.createCell(2).setCellValue(sumaTiros3 / filasDatos);
            filaMedias.createCell(3).setCellValue(sumaLibres / filasDatos);
            filaMedias.createCell(4).setCellValue(sumaMetidos2 / filasDatos);
            filaMedias.createCell(5).setCellValue(sumaMetidos3 / filasDatos);
            filaMedias.createCell(6).setCellValue(sumaMetidosLibres / filasDatos);
            filaMedias.createCell(7).setCellValue(mediaFG);
            filaMedias.createCell(8).setCellValue(mediaEFG);
            filaMedias.createCell(9).setCellValue(mediaTS);
            filaMedias.createCell(10).setCellValue(mediaValoracion);
        }

        for (int col = 0; col < datos[0].length; col++) {
            hoja.setColumnWidth(col, 20 * 256);
        }

        try (FileOutputStream salida = new FileOutputStream(nombreArchivo)) {
            libroExcel.write(salida);
        } catch (IOException ex) {
            ex.printStackTrace();
        }

        libroExcel.close();
    }

    private static double getNumericValue(Cell cell) {
        if (cell == null) {
            return 0;
        }
        switch (cell.getCellType()) {
            case NUMERIC:
                return cell.getNumericCellValue();
            case STRING:
                try {
                    return Double.parseDouble(cell.getStringCellValue());
                } catch (NumberFormatException e) {
                    return 0;
                }
            default:
                return 0;
        }
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Insertar_datos;
    private javax.swing.JTextField NombreJugador;
    private javax.swing.JPanel PanelDatos1;
    private javax.swing.JPanel PanelDatos2;
    private javax.swing.JTabbedPane PanelTabuladoDatos;
    private javax.swing.JSpinner T_2Puntos;
    private javax.swing.JSpinner T_2PuntosMetidos;
    private javax.swing.JSpinner T_3Puntos;
    private javax.swing.JSpinner T_3PuntosMetidos;
    private javax.swing.JSpinner T_Libres;
    private javax.swing.JSpinner T_LibresMetidos;
    private javax.swing.JSpinner T_asistencias;
    private javax.swing.JSpinner T_perdidas;
    private javax.swing.JSpinner T_rebotes;
    private javax.swing.JSpinner T_robos;
    private javax.swing.JSpinner T_taponesAfavor;
    private javax.swing.JSpinner T_taponesRecibidos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
