/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.estadisticasnba;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import javax.swing.JOptionPane;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import java.awt.Color;
import java.io.IOException;
import javax.swing.JFrame;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.ChartUtils;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author dl260
 */
public class NBAversion3 extends javax.swing.JFrame {

    /**
     * Creates new form PruebaNBAJFrame
     */
    public NBAversion3() {
        initComponents();
        
        equiposBox.setSelectedItem("Equipo1");
        actualizarJugadores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        equiposBox = new javax.swing.JComboBox<>();
        jugadoresBox = new javax.swing.JComboBox<>();
        Btn_guardar = new javax.swing.JButton();
        PanelTabuladoDatos = new javax.swing.JTabbedPane();
        PanelDatos1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        T_2Puntos = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        T_2PuntosMetidos = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        T_3Puntos = new javax.swing.JSpinner();
        T_3PuntosMetidos = new javax.swing.JSpinner();
        T_Libres = new javax.swing.JSpinner();
        T_LibresMetidos = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        PanelDatos2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        T_rebotes = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        T_taponesRecibidos = new javax.swing.JSpinner();
        T_asistencias = new javax.swing.JSpinner();
        T_robos = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        T_taponesAfavor = new javax.swing.JSpinner();
        T_perdidas = new javax.swing.JSpinner();
        btn_grafica = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        equiposBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Equipo1", "Equipo2" }));
        equiposBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equiposBoxActionPerformed(evt);
            }
        });
        getContentPane().add(equiposBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 30, 220, 40));

        jugadoresBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jugadoresBoxActionPerformed(evt);
            }
        });
        getContentPane().add(jugadoresBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 200, 40));

        Btn_guardar.setText("Guardar");
        Btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_guardarActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 150, 40));

        PanelTabuladoDatos.setMinimumSize(new java.awt.Dimension(100, 100));

        PanelDatos1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Tiros de 2 puntos");
        PanelDatos1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 30));
        PanelDatos1.add(T_2Puntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 100, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Tiros de 2 metidos");
        PanelDatos1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 140, 30));
        PanelDatos1.add(T_2PuntosMetidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 100, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Tiros de 3 puntos");
        PanelDatos1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 130, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Tiros de 3 metidos");
        PanelDatos1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 140, 30));
        PanelDatos1.add(T_3Puntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 100, 30));
        PanelDatos1.add(T_3PuntosMetidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 100, 30));
        PanelDatos1.add(T_Libres, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 100, 30));
        PanelDatos1.add(T_LibresMetidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 100, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Tiros Libres");
        PanelDatos1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 130, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Tiros Libres metidos");
        PanelDatos1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 140, 30));

        PanelTabuladoDatos.addTab("Datos1", PanelDatos1);

        PanelDatos2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Tapones a favor");
        PanelDatos2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 100, 30));
        PanelDatos2.add(T_rebotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 100, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Tapones reibidos");
        PanelDatos2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 110, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Asistencias");
        PanelDatos2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 100, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Robos");
        PanelDatos2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 100, 30));
        PanelDatos2.add(T_taponesRecibidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 100, 30));
        PanelDatos2.add(T_asistencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 100, 30));
        PanelDatos2.add(T_robos, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 100, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Rebotes");
        PanelDatos2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Perdidas");
        PanelDatos2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 100, 30));
        PanelDatos2.add(T_taponesAfavor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 100, 30));
        PanelDatos2.add(T_perdidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 100, 30));

        PanelTabuladoDatos.addTab("Datos2", PanelDatos2);

        getContentPane().add(PanelTabuladoDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 490, 220));

        btn_grafica.setText("Grafica");
        btn_grafica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_graficaMouseClicked(evt);
            }
        });
        getContentPane().add(btn_grafica, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 140, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void equiposBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equiposBoxActionPerformed
        actualizarJugadores();
    }//GEN-LAST:event_equiposBoxActionPerformed

    private void jugadoresBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jugadoresBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jugadoresBoxActionPerformed

    private void Btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_guardarActionPerformed
        String equipoSeleccionado = (String) equiposBox.getSelectedItem();
        String jugadorSeleccionado = (String) jugadoresBox.getSelectedItem();

        if (jugadorSeleccionado == null || equipoSeleccionado == null) {
            JOptionPane.showMessageDialog(this, "Por favor, selecciona un equipo y un jugador.");
            return;
        }

        try {
            int tiros2 = (int) T_2Puntos.getValue();
            int tirosMetidos2 = (int) T_2PuntosMetidos.getValue();
            int tiros3 = (int) T_3Puntos.getValue();
            int tirosMetidos3 = (int) T_3PuntosMetidos.getValue();
            int libres = (int) T_Libres.getValue();
            int libresMetidos = (int) T_LibresMetidos.getValue();
            int rebotes = (int) T_rebotes.getValue();
            int asistencias = (int) T_asistencias.getValue();
            int robos = (int) T_robos.getValue();
            int taponesAFavor = (int) T_taponesAfavor.getValue();
            int perdidas = (int) T_perdidas.getValue();
            int taponesRecibidos = (int) T_taponesRecibidos.getValue();

            File archivoExcel = new File(equipoSeleccionado + ".xlsx");
            Workbook libro;
            Sheet hoja;

            if (archivoExcel.exists()) {
                try (FileInputStream fis = new FileInputStream(archivoExcel)) {
                    libro = new XSSFWorkbook(fis);
                }
            } else {
                libro = new XSSFWorkbook();
            }

            hoja = libro.getSheet(jugadorSeleccionado);
            if (hoja == null) {
                hoja = libro.createSheet(jugadorSeleccionado);
                Row encabezado = hoja.createRow(0);
                encabezado.createCell(0).setCellValue("Tiros de 2");
                encabezado.createCell(1).setCellValue("Tiros de 2 Metidos");
                encabezado.createCell(2).setCellValue("Tiros de 3");
                encabezado.createCell(3).setCellValue("Tiros de 3 Metidos");
                encabezado.createCell(4).setCellValue("Libres");
                encabezado.createCell(5).setCellValue("Libres Metidos");
                encabezado.createCell(6).setCellValue("Rebotes");
                encabezado.createCell(7).setCellValue("Asistencias");
                encabezado.createCell(8).setCellValue("Robos");
                encabezado.createCell(9).setCellValue("Tapones a Favor");
                encabezado.createCell(10).setCellValue("Perdidas");
                encabezado.createCell(11).setCellValue("Tapones Recibidos");
                
                encabezado.setHeightInPoints(25);
            }

            int ultimaFila = hoja.getLastRowNum() + 1;
            Row fila = hoja.createRow(ultimaFila);
            fila.createCell(0).setCellValue(tiros2);
            fila.createCell(1).setCellValue(tirosMetidos2);
            fila.createCell(2).setCellValue(tiros3);
            fila.createCell(3).setCellValue(tirosMetidos3);
            fila.createCell(4).setCellValue(libres);
            fila.createCell(5).setCellValue(libresMetidos);
            fila.createCell(6).setCellValue(rebotes);
            fila.createCell(7).setCellValue(asistencias);
            fila.createCell(8).setCellValue(robos);
            fila.createCell(9).setCellValue(taponesAFavor);
            fila.createCell(10).setCellValue(perdidas);
            fila.createCell(11).setCellValue(taponesRecibidos);

            for (int col = 0; col <= 11; col++) {
                hoja.setColumnWidth(col, 20 * 256);
            }
            
            actualizarHojaMedias(libro, equipoSeleccionado);

            try (FileOutputStream fos = new FileOutputStream(archivoExcel)) {
                libro.write(fos);
            }
            libro.close();

            JOptionPane.showMessageDialog(this, "Estadísticas guardadas correctamente.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al guardar estadísticas: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_Btn_guardarActionPerformed

    private void btn_graficaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_graficaMouseClicked
        String equipoSeleccionado = (String) equiposBox.getSelectedItem();
        String jugadorSeleccionado = (String) jugadoresBox.getSelectedItem();

        if (equipoSeleccionado == null || jugadorSeleccionado == null) {
            JOptionPane.showMessageDialog(this, "Por favor, selecciona un equipo y un jugador.");
            return;
        }

        File archivoExcel = new File(equipoSeleccionado + ".xlsx");
        if (!archivoExcel.exists()) {
            JOptionPane.showMessageDialog(this, "El archivo del equipo seleccionado no existe.");
            return;
        }

        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        try (FileInputStream fis = new FileInputStream(archivoExcel)) {
            Workbook libro = new XSSFWorkbook(fis);
            Sheet hoja = libro.getSheet(jugadorSeleccionado);

            if (hoja == null) {
                JOptionPane.showMessageDialog(this, "No hay datos para el jugador seleccionado.");
                return;
            }

            Row encabezado = hoja.getRow(0); // Encabezados de las columnas
            if (encabezado == null) {
                JOptionPane.showMessageDialog(this, "No hay encabezados en la hoja del jugador.");
                return;
            }

            // Identificar las columnas relevantes
            int colTiros2 = -1;
            int colTiros3 = -1;
            int colTirosLibres = -1;

            for (int i = 0; i < encabezado.getLastCellNum(); i++) {
                String categoria = encabezado.getCell(i).getStringCellValue();
                switch (categoria) {
                    case "Tiros de 2 Metidos":
                        colTiros2 = i;
                        break;
                    case "Tiros de 3 Metidos":
                        colTiros3 = i;
                        break;
                    case "Libres Metidos":
                        colTirosLibres = i;
                        break;
                }
            }

            if (colTiros2 == -1 || colTiros3 == -1 || colTirosLibres == -1) {
                JOptionPane.showMessageDialog(this, "No se encontraron todas las columnas necesarias (tiros2, tiros3, tirosLibres).");
                return;
            }

            // Procesar las filas de datos (partidos)
            for (int i = 1; i <= hoja.getLastRowNum(); i++) { // Comenzar en la fila 1 (saltar encabezado)
                Row fila = hoja.getRow(i);
                if (fila == null) continue;

                try {
                    int tirosMetidos2 = (int) fila.getCell(colTiros2).getNumericCellValue();
                    int tirosMetidos3 = (int) fila.getCell(colTiros3).getNumericCellValue();
                    int tirosLibresMetidos = (int) fila.getCell(colTirosLibres).getNumericCellValue();

                    // Calcular puntos totales del partido
                    int puntosTotales = tirosMetidos2 + tirosMetidos3 + tirosLibresMetidos;

                    // Añadir al dataset
                    dataset.addValue(puntosTotales, "Puntos", "Partido " + i);
                } catch (Exception e) {
                    System.err.println("Error al procesar la fila " + i + ": " + e.getMessage());
                }
            }

            libro.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al leer el archivo Excel: " + e.getMessage());
            e.printStackTrace();
            return;
        }

        // Crear el gráfico
        JFreeChart grafico = ChartFactory.createBarChart(
            "Puntos por Partido de " + jugadorSeleccionado, // Título
            "Partidos",                                    // Etiqueta del eje X
            "Puntos",                                      // Etiqueta del eje Y
            dataset                                        // Datos
        );

        // Personalizar el gráfico
        CategoryPlot plot = grafico.getCategoryPlot();
        BarRenderer renderer = (BarRenderer) plot.getRenderer();
        renderer.setSeriesPaint(0, Color.BLUE); // Cambiar el color de las barras a azul

        // Mostrar el gráfico en una nueva ventana
        JFrame frame = new JFrame("Gráfico de Puntos por Partido");
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.setSize(800, 600);
        frame.add(new ChartPanel(grafico));
        frame.setVisible(true);

        // Guardar el gráfico como archivo JPG
        try {
            File archivo = new File("grafico_puntos_" + jugadorSeleccionado + ".jpg");
            ChartUtils.saveChartAsJPEG(archivo, grafico, 800, 600);
            JOptionPane.showMessageDialog(this, "Gráfico guardado como: " + archivo.getAbsolutePath());
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error al guardar el gráfico: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_graficaMouseClicked

    
    private void actualizarJugadores() {
        String equipoSeleccionado = (String) equiposBox.getSelectedItem();
        jugadoresBox.removeAllItems();

        if ("Equipo1".equals(equipoSeleccionado)) {
            jugadoresBox.addItem("Jugador 1A");
            jugadoresBox.addItem("Jugador 2A");
            jugadoresBox.addItem("Jugador 3A");
            jugadoresBox.addItem("Jugador 4A");
            jugadoresBox.addItem("Jugador 5A");
        } else if ("Equipo2".equals(equipoSeleccionado)) {
            jugadoresBox.addItem("Jugador 1B");
            jugadoresBox.addItem("Jugador 2B");
            jugadoresBox.addItem("Jugador 3B");
            jugadoresBox.addItem("Jugador 4B");
            jugadoresBox.addItem("Jugador 5B");
        }
    }
    
    private void actualizarHojaMedias(Workbook libro, String equipoSeleccionado) {
        Sheet hojaMedias = libro.getSheet("Medias");
        if (hojaMedias == null) {
            hojaMedias = libro.createSheet("Medias");
            Row encabezado = hojaMedias.createRow(0);
            encabezado.createCell(0).setCellValue("Jugador");
            encabezado.createCell(1).setCellValue("Media Tiros de 2");
            encabezado.createCell(2).setCellValue("Media Tiros de 2 Metidos");
            encabezado.createCell(3).setCellValue("Media Tiros de 3");
            encabezado.createCell(4).setCellValue("Media Tiros de 3 Metidos");
            encabezado.createCell(5).setCellValue("Media Libres");
            encabezado.createCell(6).setCellValue("Media Libres Metidos");
            encabezado.createCell(7).setCellValue("Media Rebotes");
            encabezado.createCell(8).setCellValue("Media Asistencias");
            encabezado.createCell(9).setCellValue("Media Robos");
            encabezado.createCell(10).setCellValue("Media Tapones a Favor");
            encabezado.createCell(11).setCellValue("Media Perdidas");
            encabezado.createCell(12).setCellValue("Media Tapones Recibidos");
            
            encabezado.setHeightInPoints(25);
        }

        int filaMedias = 1;
        for (int i = 0; i < jugadoresBox.getItemCount(); i++) {
            String jugador = jugadoresBox.getItemAt(i);
            Sheet hojaJugador = libro.getSheet(jugador);
            if (hojaJugador != null) {
                Row filaMedia = hojaMedias.getRow(filaMedias);
                if (filaMedia == null) {
                    filaMedia = hojaMedias.createRow(filaMedias);
                }
                filaMedia.createCell(0).setCellValue(jugador);

                for (int col = 0; col <= 11; col++) {
                    double media = calcularMedia(hojaJugador, col);
                    filaMedia.createCell(col + 1).setCellValue(media);
                }
                filaMedias++;
            }
        }
        for (int col = 0; col <= 12; col++) {
            hojaMedias.setColumnWidth(col, 25 * 256);
        }
    }
    
    private double calcularMedia(Sheet hoja, int columna) {
        double suma = 0;
        int filas = hoja.getLastRowNum();
        for (int i = 1; i <= filas; i++) {
            Row fila = hoja.getRow(i);
            suma += fila.getCell(columna).getNumericCellValue();
        }
        return filas == 0 ? 0 : suma / filas;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NBAversion3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NBAversion3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NBAversion3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NBAversion3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NBAversion3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_guardar;
    private javax.swing.JPanel PanelDatos1;
    private javax.swing.JPanel PanelDatos2;
    private javax.swing.JTabbedPane PanelTabuladoDatos;
    private javax.swing.JSpinner T_2Puntos;
    private javax.swing.JSpinner T_2PuntosMetidos;
    private javax.swing.JSpinner T_3Puntos;
    private javax.swing.JSpinner T_3PuntosMetidos;
    private javax.swing.JSpinner T_Libres;
    private javax.swing.JSpinner T_LibresMetidos;
    private javax.swing.JSpinner T_asistencias;
    private javax.swing.JSpinner T_perdidas;
    private javax.swing.JSpinner T_rebotes;
    private javax.swing.JSpinner T_robos;
    private javax.swing.JSpinner T_taponesAfavor;
    private javax.swing.JSpinner T_taponesRecibidos;
    private javax.swing.JButton btn_grafica;
    private javax.swing.JComboBox<String> equiposBox;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> jugadoresBox;
    // End of variables declaration//GEN-END:variables
}
